name:                PokerHandHaskell
version:             0.1.0.0
github:              "iboss-ptk/PokerHandHaskell"
license:             BSD3
author:              "Supanat Potiwarakorn"
maintainer:          "supanat.ptk@gmail.com"
copyright:           "2019 Supanat Potiwarakorn"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/iboss-ptk/PokerHandHaskell#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  PokerHandHaskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - PokerHandHaskell
    - text

tests:
  PokerHandHaskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - PokerHandHaskell
    - QuickCheck
    - hspec
